gitwok:
  commit:
    prompt:
      scope: true
      breaking: true
      body: true
      footers: true
    type:
      - fix
      - feat
      - build
      - chore
      - ci
      - docs
      - perf
      - refactor
      - style
      - test
    scope:
      - readme.md
      - release
