name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build & Test
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build module
      run: go build -v .

    - name: Test and gen-cov
      run: |
        go test -v ./... -coverprofile=coverage.txt -covermode=atomic

    - name: Upload cov report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        verbose: true
