on:
  push:
    tags:
      - 'v*'

name: CD

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # body_path: TODO: changelog
          draft: false
          prerelease: false
      
      - name: Bump Homebrew tap formula
        uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: gitwok
          homebrew-tap: Roytangrb/homebrew-gitwok
          base-branch: main
          download-url: https://github.com/Roytangrb/gitwok/archive/${{ github.event.release.tag_name }}.tar.gz
          commit-message: Release {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.BREW_TAP_REPO_TOKEN }}